In [1]:
import requests
from bs4 import BeautifulSoup
import re

# Step 1: Define the URL to scrape
url =  "https://support.techsmith.com/hc/en-us/community/topics/360001711131-Camtasia-Windows-"

# Step 2: Send an HTTP GET request and fetch the HTML content
response = requests.get(url)
html_content = response.text

# Step 3: Parse the HTML content using BeautifulSoup
soup = BeautifulSoup(html_content, 'html.parser')

# Step 4: Extract complaint information
complaints = []

# You'll need to inspect the HTML structure of the webpage to identify the elements containing complaint information
# and extract them accordingly using BeautifulSoup and CSS selectors or other methods.

# Example:
complaint_elements = soup.find_all('div', class_='complaint')

for complaint_element in complaint_elements:
    complaint_text = complaint_element.get_text()
    complaints.append(complaint_text)

# Step 5: Categorize complaints as High, Medium, or Low based on some criteria
high_priority_keywords = ['urgent', 'critical', 'emergency']
medium_priority_keywords = ['delayed', 'inconvenient']
low_priority_keywords = ['minor', 'cosmetic']

categorized_complaints = []

for complaint in complaints:
    complaint_lower = complaint.lower()
    if any(keyword in complaint_lower for keyword in high_priority_keywords):
        category = 'High'
    elif any(keyword in complaint_lower for keyword in medium_priority_keywords):
        category = 'Medium'
    elif any(keyword in complaint_lower for keyword in low_priority_keywords):
        category = 'Low'
    else:
        category = 'Uncategorized'
    
    categorized_complaints.append((complaint, category))

# Step 6: Display or store the categorized complaints
for complaint, category in categorized_complaints:
    print(f"Category: {category}")
    print(f"Complaint: {complaint}")
    print()

# You can further refine and adapt this code to suit the specific structure and requirements of the website you are scraping.

In [2]:
print(categorized_complaints)

[]

In [3]:
import requests
from bs4 import BeautifulSoup

# Define the URL to scrape
url = 'https://support.techsmith.com/hc/en-us/community/topics/360001711131-Camtasia-Windows-'

# Send an HTTP GET request and fetch the HTML content
response = requests.get(url)
html_content = response.text

# Parse the HTML content using BeautifulSoup
soup = BeautifulSoup(html_content, 'html.parser')

# Define keywords to categorize complaints
high_priority_keywords = ['urgent', 'critical', 'emergency']
medium_priority_keywords = ['delayed', 'inconvenient']
low_priority_keywords = ['minor', 'cosmetic']

# Initialize lists to store categorized complaints
high_priority_complaints = []
medium_priority_complaints = []
low_priority_complaints = []

# Find elements containing complaints (You need to inspect the webpage's structure to get the correct selectors)
complaint_elements = soup.find_all('div', class_='community-topic-title')

for complaint_element in complaint_elements:
    complaint_text = complaint_element.get_text().strip().lower()

    if any(keyword in complaint_text for keyword in high_priority_keywords):
        high_priority_complaints.append(complaint_text)
    elif any(keyword in complaint_text for keyword in medium_priority_keywords):
        medium_priority_complaints.append(complaint_text)
    elif any(keyword in complaint_text for keyword in low_priority_keywords):
        low_priority_complaints.append(complaint_text)

# Display or process the categorized complaints
print("High Priority Complaints:")
for complaint in high_priority_complaints:
    print(complaint)

print("\nMedium Priority Complaints:")
for complaint in medium_priority_complaints:
    print(complaint)

print("\nLow Priority Complaints:")
for complaint in low_priority_complaints:
    print(complaint)

High Priority Complaints:

Medium Priority Complaints:

Low Priority Complaints:

In [1]:
import requests
from bs4 import BeautifulSoup

# Define the URL you want to scrape
url = 'https://www.politifact.com/'

# Send an HTTP GET request to the URL
response = requests.get(url)

# Check if the request was successful (status code 200)
if response.status_code == 200:
    # Parse the HTML content of the page using BeautifulSoup
    soup = BeautifulSoup(response.text, 'html.parser')

    # You can now navigate the HTML and extract information
    # For example, let's extract and print all the links on the page
    for link in soup.find_all('a'):
        print(link.get('href'))
else:
    print('Failed to retrieve the web page. Status code:', response.status_code)

/
#
/membership/
/california/
/florida/
/illinois/
/iowa/
/missouri/
/new-york/
/north-carolina/
/pennsylvania/
/texas/
/virginia/
/west-virginia/
/vermont/
/wisconsin/
/michigan/
/issues/
/facebook-fact-checks/
/coronavirus/
/health-check/
/immigration/
https://www.politifact.com/article/2022/jun/09/political-extremism-public-square-resource-journal/
/taxes/
/marijuana/
/environment/
/crime/
/guns/
/foreign-policy/
/lgbtq/
/personalities/
/personalities/joe-biden/
/personalities/kamala-harris/
/personalities/charles-schumer/
/personalities/mitch-mcconnell/
/personalities/bernie-sanders/
/personalities/nancy-pelosi/
/personalities/donald-trump/
/punditfact/
/personalities/tucker-carlson/
/personalities/sean-hannity/
/personalities/rachel-maddow/
/personalities/blog-posting/
/videos/
/2020/
/factchecks/list/?ruling=true
/factchecks/list/?ruling=mostly-true
/factchecks/list/?ruling=half-true
/factchecks/list/?ruling=barely-true
/factchecks/list/?ruling=false
/factchecks/list/?ruling=pants-fire
/truth-o-meter/promises/biden-promise-tracker/?ruling=true
/truth-o-meter/promises/trumpometer/?ruling=true
/truth-o-meter/promises/obameter/?ruling=true
/truth-o-meter/promises/list/
/article/2018/feb/12/principles-truth-o-meter-politifacts-methodology-i/
/staff/
/who-pays-for-politifact/
/media-kit/
/suggest/statement/
/corrections-and-updates/
/membership/
https://twitter.com/Politifact/
https://www.facebook.com/politifact/

/membership/
/personalities/donald-trump/
/factchecks/2023/sep/14/donald-trump/trump-said-under-desantis-florida-demanded-everybo/
/personalities/thom-tillis/
/factchecks/2023/sep/08/thom-tillis/tillis-email-omits-key-details-of-democrats-propos/
/personalities/chris-christie/
/factchecks/2023/sep/08/chris-christie/chris-christie-knocks-ron-desantis-for-floridas-ri/
/personalities/lakeshia-myers/
/factchecks/2023/sep/08/lakeshia-myers/its-true-wis-voters-did-not-have-standard-notice-o/
/personalities/isabel-brown/
/factchecks/2023/sep/07/isabel-brown/are-americans-today-making-less-than-at-the-height/
/personalities/facebook-posts/
/factchecks/2023/sep/06/facebook-posts/no-theres-no-florida-law-requiring-fathers-take-a/
/personalities/donald-trump/
/factchecks/2023/sep/14/donald-trump/trump-said-he-doesnt-know-who-gave-fauci-a-commend/
/personalities/facebook-posts/
/factchecks/2023/sep/14/facebook-posts/old-baseless-rumors-about-clinton-snuff-film-persi/
/personalities/instagram-posts/
/factchecks/2023/sep/14/instagram-posts/bidens-remarks-about-extreme-weather-events-were-t/
/personalities/facebook-posts/
/factchecks/2023/sep/14/facebook-posts/este-video-del-derrumbamiento-de-un-edificio-en-ma/
/personalities/tiktok-posts/
/factchecks/2023/sep/14/tiktok-posts/hawaii-isnt-home-to-tons-of-lithium-despite-basele/
/personalities/donald-trump/
/factchecks/2023/sep/14/donald-trump/trump-said-under-desantis-florida-demanded-everybo/
/personalities/facebook-posts/
/factchecks/2023/sep/14/facebook-posts/claim-that-the-view-hosts-threatened-to-resign-if/
/personalities/facebook-posts/
/factchecks/2023/sep/13/facebook-posts/no-cnn-did-not-break-news-about-a-pentagon-plan-to/
/personalities/viral-image/
/factchecks/2023/sep/13/viral-image/this-isnt-an-authentic-video-of-vice-president-kam/
/personalities/viral-image/
/factchecks/2023/sep/13/viral-image/on-maui-66-people-are-still-missing-after-the-wild/
/factchecks/list/
/article/2023/sep/13/why-the-cdc-has-recommended-new-covid-boosters-for/
/article/2023/sep/13/why-the-cdc-has-recommended-new-covid-boosters-for/
/article/2023/sep/13/house-speaker-kevin-mccarthy-orders-impeachment-in/
/article/2023/sep/13/house-speaker-kevin-mccarthy-orders-impeachment-in/
/article/2023/sep/12/what-are-smart-cities-and-why-are-conspiracy-theor/
/article/2023/sep/12/what-are-smart-cities-and-why-are-conspiracy-theor/
/article/2023/sep/12/cdc-faces-conundrum-over-recommending-new-covid-19/
/article/2023/sep/12/cdc-faces-conundrum-over-recommending-new-covid-19/
/article/2023/sep/11/a-possible-house-impeachment-investigation-of-joe/
/article/2023/sep/11/a-possible-house-impeachment-investigation-of-joe/
/article/2023/sep/11/heat-related-deaths-are-up-and-not-just-because-it/
/article/2023/sep/11/heat-related-deaths-are-up-and-not-just-because-it/
/article/2023/sep/08/what-are-fentanyl-patches-does-narcan-work-for-fen/
/article/2023/sep/08/what-are-fentanyl-patches-does-narcan-work-for-fen/
/article/2023/sep/08/covid-19-lockdowns-returning-heres-why-public-heal/
/article/2023/sep/08/covid-19-lockdowns-returning-heres-why-public-heal/
/article/2023/sep/06/could-the-14th-amendment-keep-donald-trump-off-the/
/article/2023/sep/06/could-the-14th-amendment-keep-donald-trump-off-the/
/article/2023/sep/05/ask-politifact-why-are-some-border-gates-open-in-a/
/article/2023/sep/05/ask-politifact-why-are-some-border-gates-open-in-a/
/article/list/
/personalities/joe-biden/
/truth-o-meter/promises/biden-promise-tracker/promise/1595/forgive-student-loan-debt-public-colleges-and-univ/
/personalities/joe-biden/
/truth-o-meter/promises/biden-promise-tracker/promise/1609/increase-refugee-admissions/
/personalities/joe-biden/
/truth-o-meter/promises/biden-promise-tracker/promise/1591/expand-broadband-or-wireless-broadband-5g-every-am/
/personalities/joe-biden/
/truth-o-meter/promises/biden-promise-tracker/promise/1527/expand-justice-department-power-address-police-mis/
/personalities/joe-biden/
/truth-o-meter/promises/biden-promise-tracker/promise/1519/use-national-commission-address-policing-issues/
/personalities/thom-tillis/
/factchecks/2023/sep/08/thom-tillis/tillis-email-omits-key-details-of-democrats-propos/
/personalities/chris-christie/
/factchecks/2023/sep/08/chris-christie/chris-christie-knocks-ron-desantis-for-floridas-ri/
/personalities/lakeshia-myers/
/factchecks/2023/sep/08/lakeshia-myers/its-true-wis-voters-did-not-have-standard-notice-o/
/personalities/isabel-brown/
/factchecks/2023/sep/07/isabel-brown/are-americans-today-making-less-than-at-the-height/
/personalities/facebook-posts/
/factchecks/2023/sep/06/facebook-posts/no-theres-no-florida-law-requiring-fathers-take-a/
/personalities/joe-biden/
/personalities/joe-biden/
/personalities/citizens-sanity/
/personalities/citizens-sanity/
/personalities/jeh-johnson/
/personalities/jeh-johnson/
/personalities/francis-suarez/
/personalities/francis-suarez/
/personalities/donald-trump/
/personalities/donald-trump/
#
https://apnews.com/article/fact-check-bill-gates-climate-change-trees-global-warming-758018152043
https://apnews.com/article/fact-check-bill-gates-climate-change-trees-global-warming-758018152043
https://www.usatoday.com/story/news/factcheck/2023/09/14/romney-not-seeking-senate-reelection-but-isnt-resigning-fact-check/70853207007/
https://www.usatoday.com/story/news/factcheck/2023/09/14/romney-not-seeking-senate-reelection-but-isnt-resigning-fact-check/70853207007/
https://www.factcheck.org/2023/09/posts-misrepresent-use-of-floodgates-at-southern-border/
https://www.factcheck.org/2023/09/posts-misrepresent-use-of-floodgates-at-southern-border/
https://www.cnn.com/2023/09/14/politics/fact-check-trump-claims-about-biden-economy/index.html
https://www.cnn.com/2023/09/14/politics/fact-check-trump-claims-about-biden-economy/index.html
https://apnews.com/article/fact-check-us-ukraine-6-billion-aid-987942991352
https://apnews.com/article/fact-check-us-ukraine-6-billion-aid-987942991352
/around-the-web/
/article/2018/feb/12/principles-truth-o-meter-politifacts-methodology-i/
/staff/
/who-pays-for-politifact/
/membership/
#
#
/personalities/
/personalities/joe-biden/
/personalities/kamala-harris/
/personalities/charles-schumer/
/personalities/mitch-mcconnell/
/personalities/bernie-sanders/
/personalities/nancy-pelosi/
/personalities/donald-trump/
/california/
/florida/
/illinois/
/iowa/
/missouri/
/new-york/
/north-carolina/
/pennsylvania/
/texas/
/virginia/
/west-virginia/
/vermont/
/wisconsin/
/michigan/
/article/2018/feb/12/principles-truth-o-meter-politifacts-methodology-i/
/staff/
/who-pays-for-politifact/
/media-kit/
/corrections-and-updates/
/rss/all/
/rss/factchecks/
/suggest/statement/
https://twitter.com/Politifact/
https://www.facebook.com/politifact/
/copyright/
/privacy/
/copyright/

In [4]:
import pandas as pd
df = pd.read_csv("C:\\Users\\lenovo\\Downloads\\bassic_EDA.csv")

In [5]:
df.head(5)

,Unnamed: 0,Name,Team
0,0,Mohak Singhania,NaN
1,1,Aviral Jain,NaN
2,2,Abhay Kumar Arora,"Abhay , Khushi , Devyanne , Aditi , Rajat ,Naincy"
3,3,Anjali Patel,Anjali Patel\nSonali Jain\nRahul Sharma \nMait...
4,4,Shreet pathrikar,NaN

In [6]:
df

,Unnamed: 0,Name,Team
0,0,Mohak Singhania,NaN
1,1,Aviral Jain,NaN
2,2,Abhay Kumar Arora,"Abhay , Khushi , Devyanne , Aditi , Rajat ,Naincy"
3,3,Anjali Patel,Anjali Patel\nSonali Jain\nRahul Sharma \nMait...
4,4,Shreet pathrikar,NaN
5,5,Arindam Raha,NaN
6,6,Prachi Kumbhkar,NaN
7,7,Chirag bhawsar,NaN
8,8,Rahul Singh Rajawat,NaN
9,9,Akshita Verma,"Tehrim Fatma, Mansi Yadav, Shafaq Hashmi, Ranj..."
10,10,Shafaq Hashmi,"Shafaq Hashmi, Tehrim Fatma, Akshita Verma, Ra..."
11,11,Tehrim Fatma,"Tehrim Fatma, Ranjana Singh, Akshita Verma, Ma..."
12,12,Yashraj Singh Rajawat,NaN
13,13,Ranjana singh,"Ranjana,akshita ,tehreem ,shafaq,mansi"
14,14,Mansi Yadav,"Tehreem, Shafaq, Akshita, Ranjana, Mansi"
15,15,Yuvraj singh sisodiya,NaN
16,16,prashnat parmar,prashant parmar & himanshu vaish
17,17,Anabhi Kori,"Anabhi , Shruti"
18,18,Gracy Jain,"Aviral Jain , Gracy Jain"
19,19,Shruti Ladke,"Shruti Ladke, Anabhi Kori"

In [8]:
column = "Name"

df_no_duplicates = df.drop_duplicates(subset= column, keep='first')
df_no_duplicates

,Unnamed: 0,Name,Team
0,0,Mohak Singhania,NaN
1,1,Aviral Jain,NaN
2,2,Abhay Kumar Arora,"Abhay , Khushi , Devyanne , Aditi , Rajat ,Naincy"
3,3,Anjali Patel,Anjali Patel\nSonali Jain\nRahul Sharma \nMait...
4,4,Shreet pathrikar,NaN
5,5,Arindam Raha,NaN
6,6,Prachi Kumbhkar,NaN
7,7,Chirag bhawsar,NaN
8,8,Rahul Singh Rajawat,NaN
9,9,Akshita Verma,"Tehrim Fatma, Mansi Yadav, Shafaq Hashmi, Ranj..."
10,10,Shafaq Hashmi,"Shafaq Hashmi, Tehrim Fatma, Akshita Verma, Ra..."
11,11,Tehrim Fatma,"Tehrim Fatma, Ranjana Singh, Akshita Verma, Ma..."
12,12,Yashraj Singh Rajawat,NaN
13,13,Ranjana singh,"Ranjana,akshita ,tehreem ,shafaq,mansi"
14,14,Mansi Yadav,"Tehreem, Shafaq, Akshita, Ranjana, Mansi"
15,15,Yuvraj singh sisodiya,NaN
16,16,prashnat parmar,prashant parmar & himanshu vaish
17,17,Anabhi Kori,"Anabhi , Shruti"
18,18,Gracy Jain,"Aviral Jain , Gracy Jain"
19,19,Shruti Ladke,"Shruti Ladke, Anabhi Kori"

In [12]:
df.shape

(20, 3)

In [13]:
column_to_check = "Team"
filtered_df = df[df[column_to_check].isna()]

In [14]:
filtered_df

    Unnamed: 0                    Name Team
0            0        Mohak Singhania   NaN
1            1             Aviral Jain  NaN
4            4        Shreet pathrikar  NaN
5            5            Arindam Raha  NaN
6            6        Prachi Kumbhkar   NaN
7            7          Chirag bhawsar  NaN
8            8     Rahul Singh Rajawat  NaN
12          12  Yashraj Singh Rajawat   NaN
15          15   Yuvraj singh sisodiya  NaN

In [15]:
column_to_check = "Team"
filtered_df1 = df[df[column_to_check].notna()]

In [16]:
filtered_df1

,Unnamed: 0,Name,Team
2,2,Abhay Kumar Arora,"Abhay , Khushi , Devyanne , Aditi , Rajat ,Naincy"
3,3,Anjali Patel,Anjali Patel\nSonali Jain\nRahul Sharma \nMait...
9,9,Akshita Verma,"Tehrim Fatma, Mansi Yadav, Shafaq Hashmi, Ranj..."
10,10,Shafaq Hashmi,"Shafaq Hashmi, Tehrim Fatma, Akshita Verma, Ra..."
11,11,Tehrim Fatma,"Tehrim Fatma, Ranjana Singh, Akshita Verma, Ma..."
13,13,Ranjana singh,"Ranjana,akshita ,tehreem ,shafaq,mansi"
14,14,Mansi Yadav,"Tehreem, Shafaq, Akshita, Ranjana, Mansi"
16,16,prashnat parmar,prashant parmar & himanshu vaish
17,17,Anabhi Kori,"Anabhi , Shruti"
18,18,Gracy Jain,"Aviral Jain , Gracy Jain"
19,19,Shruti Ladke,"Shruti Ladke, Anabhi Kori"

In [22]:
# Define a function to remove special characters and spaces from a string
def clean_string(input_string):
    # Use regex to remove special characters and spaces
    import re
    return re.sub(r'[^a-zA-Z0-9]', '', input_string)

# Apply the function to each element in the list using a list comprehension
cleaned_column  =[]
c = [cleaned_column.append(clean_string(item)) for item in filtered_df1["Team"] for i in ]

In [25]:
cleaned_column

['AbhayKhushiDevyanneAditiRajatNaincy',
 'AnjaliPatelSonaliJainRahulSharmaMaitriJain',
 'TehrimFatmaMansiYadavShafaqHashmiRanjanaSingh',
 'ShafaqHashmiTehrimFatmaAkshitaVermaRanjanaSinghMansiYadav',
 'TehrimFatmaRanjanaSinghAkshitaVermaMansiYadavShafaqHashmi',
 'Ranjanaakshitatehreemshafaqmansi',
 'TehreemShafaqAkshitaRanjanaMansi',
 'prashantparmarhimanshuvaish',
 'AnabhiShruti',
 'AviralJainGracyJain',
 'ShrutiLadkeAnabhiKori']

In [28]:
cleaned_column[] == cleaned_column[3]

False

In [36]:
#Define a function to iterate over the lists and strings
def iterate_over_lists(list_of_strings):
    for string in list_of_strings:
        print(string)

# Apply the function to the 'ListColumn' using apply and lambda
df['Team'].apply(lambda x : x in iterate_over_lists(df["Team"][x]))

KeyError: nan

In [39]:
for x in filtered_df1["Team"] :
    print(x)

Abhay , Khushi , Devyanne , Aditi , Rajat ,Naincy
Anjali Patel
Sonali Jain
Rahul Sharma
Maitri Jain
Tehrim Fatma, Mansi Yadav, Shafaq Hashmi, Ranjana Singh
Shafaq Hashmi, Tehrim Fatma, Akshita Verma, Ranjana Singh, Mansi Yadav
Tehrim Fatma, Ranjana Singh, Akshita Verma, Mansi Yadav, Shafaq Hashmi
Ranjana,akshita ,tehreem ,shafaq,mansi
Tehreem, Shafaq, Akshita, Ranjana, Mansi
prashant parmar & himanshu vaish
Anabhi , Shruti
Aviral Jain , Gracy Jain
Shruti Ladke, Anabhi Kori

2     [A, b, h, a, y, , ,, , K, h, u, s, h, i, , ,, ...
3     [A, n, j, a, l, i, , P, a, t, e, l, \n, S, o, ...
9     [T, e, h, r, i, m, , F, a, t, m, a, ,, , M, a,...
10    [S, h, a, f, a, q, , H, a, s, h, m, i, ,, , T,...
11    [T, e, h, r, i, m, , F, a, t, m, a, ,, , R, a,...
13    [R, a, n, j, a, n, a, ,, a, k, s, h, i, t, a, ...
14    [T, e, h, r, e, e, m, ,, , S, h, a, f, a, q, ,...
16    [p, r, a, s, h, a, n, t, , p, a, r, m, a, r, ,...
17          [A, n, a, b, h, i, , ,, , S, h, r, u, t, i]
18    [A, v, i, r, a, l, , J, a, i, n, , ,, , G, r, ...
19    [S, h, r, u, t, i, , L, a, d, k, e, ,, , A, n,...
Name: Team, dtype: object

In [48]:
filtered_df1['Team'] = filtered_df1['Team'].apply(lambda x: [item.replace(" ", "") for item in x])

print(filtered_df1)

    Unnamed: 0                Name  \
2            2  Abhay Kumar Arora
3            3       Anjali Patel
9            9      Akshita Verma
10          10       Shafaq Hashmi
11          11       Tehrim Fatma
13          13       Ranjana singh
14          14         Mansi Yadav
16          16     prashnat parmar
17          17         Anabhi Kori
18          18          Gracy Jain
19          19        Shruti Ladke

                                                 Team
2   [A, b, h, a, y, , ,, , K, h, u, s, h, i, , ,, ...
3   [A, n, j, a, l, i, , P, a, t, e, l, \n, S, o, ...
9   [T, e, h, r, i, m, , F, a, t, m, a, ,, , M, a,...
10  [S, h, a, f, a, q, , H, a, s, h, m, i, ,, , T,...
11  [T, e, h, r, i, m, , F, a, t, m, a, ,, , R, a,...
13  [R, a, n, j, a, n, a, ,, a, k, s, h, i, t, a, ...
14  [T, e, h, r, e, e, m, ,, , S, h, a, f, a, q, ,...
16  [p, r, a, s, h, a, n, t, , p, a, r, m, a, r, ,...
17        [A, n, a, b, h, i, , ,, , S, h, r, u, t, i]
18  [A, v, i, r, a, l, , J, a, i, n, , ,, , G, r, ...
19  [S, h, r, u, t, i, , L, a, d, k, e, ,, , A, n,...

C:\Users\lenovo\AppData\Local\Temp\ipykernel_19548\3389226650.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df1['Team'] = filtered_df1['Team'].apply(lambda x: [item.replace(" ", "") for item in x])

In [46]:
cleaned_list = [item.strip() for item in filtered_df1["Team"]]

print(cleaned_list)

['Abhay , Khushi , Devyanne , Aditi , Rajat ,Naincy', 'Anjali Patel\nSonali Jain\nRahul Sharma \nMaitri Jain', 'Tehrim Fatma, Mansi Yadav, Shafaq Hashmi, Ranjana Singh', 'Shafaq Hashmi, Tehrim Fatma, Akshita Verma, Ranjana Singh, Mansi Yadav', 'Tehrim Fatma, Ranjana Singh, Akshita Verma, Mansi Yadav, Shafaq Hashmi', 'Ranjana,akshita ,tehreem ,shafaq,mansi', 'Tehreem, Shafaq, Akshita, Ranjana, Mansi', 'prashant parmar & himanshu vaish', 'Anabhi , Shruti', 'Aviral Jain , Gracy Jain', 'Shruti Ladke, Anabhi Kori']

In [58]:
is_unique = ~filtered_df1['Team'].duplicated(keep=False)

# Print the DataFrame with the uniqueness status
filtered_df1['IsUnique'] = is_unique

print(filtered_df1)

    Unnamed: 0                Name  \
2            2  Abhay Kumar Arora
3            3       Anjali Patel
9            9      Akshita Verma
10          10       Shafaq Hashmi
11          11       Tehrim Fatma
13          13       Ranjana singh
14          14         Mansi Yadav
16          16     prashnat parmar
17          17         Anabhi Kori
18          18          Gracy Jain
19          19        Shruti Ladke

                                                 Team  IsUnique
2   [A, b, h, a, y, , ,, , K, h, u, s, h, i, , ,, ...      True
3   [A, n, j, a, l, i, , P, a, t, e, l, \n, S, o, ...      True
9   [T, e, h, r, i, m, , F, a, t, m, a, ,, , M, a,...      True
10  [S, h, a, f, a, q, , H, a, s, h, m, i, ,, , T,...      True
11  [T, e, h, r, i, m, , F, a, t, m, a, ,, , R, a,...      True
13  [R, a, n, j, a, n, a, ,, a, k, s, h, i, t, a, ...      True
14  [T, e, h, r, e, e, m, ,, , S, h, a, f, a, q, ,...      True
16  [p, r, a, s, h, a, n, t, , p, a, r, m, a, r, ,...      True
17        [A, n, a, b, h, i, , ,, , S, h, r, u, t, i]      True
18  [A, v, i, r, a, l, , J, a, i, n, , ,, , G, r, ...      True
19  [S, h, r, u, t, i, , L, a, d, k, e, ,, , A, n,...      True

C:\Users\lenovo\AppData\Local\Temp\ipykernel_19548\4214440020.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df1['IsUnique'] = is_unique

In [68]:
def remove_special_characters(input_string):
    # Use regex to remove special characters
    import re
    return re.sub(r'[^\w\s]', '', input_string)

# Apply the function to each element in the list using list comprehension
cleaned_list = [remove_special_characters(item) for item in filtered_df1["Team"]]

print(cleaned_list)

TypeError: expected string or bytes-like object, got 'list'